version: "3"

networks:
 uwb:
   driver: bridge
  
services:
  ros-master:
   image: ros:noetic-ros-core
   hostname: ros-master
   command: roscore
   networks:
     - uwb
   restart: always
  
  uwb_tracking_ros:
   image: oz2paul/uwb_tracking_ros:noetic
   networks: 
     - uwb
   hostname: uwb_tracking
   devices:
     - /dev/ttyACM0:/dev/ttyACM0
   depends_on:
     - ros-master
   environment:
     - "ROS_HOSTNAME=uwb_tracking"
     - "ROS_MASTER_URI=http://uwb-tracking-ros_ros-master_1:11311"
   command: roslaunch uwb_tracking_ros uwb_tracking_dwm1001_non_Viz.launch
   
   restart: always