ARG FROM_IMAGE=ros:noetic-robot-focal
ARG OVERLAY_WS=/opt/ros/overlay_ws

# multi-stage for building
FROM $FROM_IMAGE AS builder

# install overlay dependencies
ARG OVERLAY_WS
WORKDIR $OVERLAY_WS

RUN mkdir ./src
RUN apt-get update && apt-get upgrade -y && apt-get autoremove -y \
    && apt-get install -y git setserial python3-pip
RUN yes | pip install pyserial numpy

# RUN . /opt/ros/$ROS_DISTRO/setup.sh && catkin init
WORKDIR $OVERLAY_WS/src
RUN git clone -b dev https://github.com/Rick-Kota/uwb-tracking-ros.git

# RUN ls
WORKDIR $OVERLAY_WS

RUN . /opt/ros/$ROS_DISTRO/setup.sh && export DEBIAN_FRONTEND=noninteractive \
    && rosdep install -y --from-paths src --ignore-src \
    && catkin_make \
    && rm -rf /var/lib/apt/lists/*

# source entrypoint setup
ENV OVERLAY_WS $OVERLAY_WS
RUN sed --in-place --expression \
      '$isource "$OVERLAY_WS/devel/setup.bash"' \
      /ros_entrypoint.sh

RUN echo ". /opt/ros/$ROS_DISTRO/setup.sh" >> /root/.bashrc && echo ". /opt/ros/overlay_ws/devel/setup.sh" >> /root/.bashrc 

# run launch file
CMD ["/bin/bash"]